### ISSUE TITLE
rename any "global" househould APIs to "generic" household APIs on the swagger site

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/generic-household-api#2]
I see it occurring in two places: on the Swagger UI url (top of the attached screenshot), and in the server dropdown box (lower portion of the attached screenshot).
![global](https://user-images.githubusercontent.com/4115079/69266841-f2d26d00-0b99-11ea-9a2d-3e3d4926ddb0.png)

**Comment by logicsandeep** [comment]
This issue is fixed.
![Uploading Screen Shot 2020-08-24 at 2.30.48 PM.png…]()
