### ISSUE TITLE
duplicate key error

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/generic-household-api#3]
![error](https://user-images.githubusercontent.com/4115079/90969202-de722680-e4c3-11ea-995a-5e92838cc8db.png)

**Comment by logicsandeep** [comment]
https://github.com/hmis-api/generic-household-api/commit/286b3b735f80af25980c448f1b445b4e67cd466a

**Comment by logicsandeep** [comment]
<img width="1404" alt="Screen Shot 2020-08-24 at 2 27 19 PM" src="https://user-images.githubusercontent.com/4108057/91082152-3d47b500-e616-11ea-8a81-e48adf1eec90.png">
This issue is fixed.
